spring.application.name: StudyNest

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
server:
  servlet:
    context-path: /studynest