spring:
  application:
    name: StudyNest
  datasource:
    url: jdbc:postgresql://postgres:5432/studynest
    username: studynest_user
    password: studynest_pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  docker:
    compose:
      enabled: false

server:
  servlet:
    context-path: /api
